### ISSUE TITLE
Blocked Flag Combinations Configuration

### ISSUE THREAD

**Issue by MithrandirCraft** [drbot7/GriefPreventionFlags#2]
I'd really like flight flags to be incompatible with having pvp allowed flags in claims. Can I currently achieve this? Or could there be an option for both flags to cancel out?

Would also be nice if flight mode got optionally disabled when receiving potion, projectile or melee damage. Any kind of damage would also do if lazy.

I think these two optional measures together should be enough to fix pvp abuse with flying.

**Comment by drbot7** [comment]
I think I could add something to the config where you can specify which claimflags can't be combined with other claimflags. It might take me a while since this is a somewhat larger feature request. The config would look something like this:
```
blocked-flag-combinations:
  set1:
    flags: [noenter, noenterplayer]
    max: 1 # you can only set at most 1 of these flags
  set2:
    flags: [allowpvp, allowflight]
    max: 1
```

For the second part, I'm not sure the best way to achieve that. When would you want the player to be able to fly again? Should they have to walk out of the claim and come back in? Wait a few seconds? The first feature you mentioned seems more feasible for this project right now. 

From what I understand of each feature's description, either one of your two mentioned features should be enough to prevent people from flying while in pvp combat, right? Your last sentence makes it seem like you believe both features must be implemented.
